//
//  HopperError.swift
//  iOS SDK
//
//  Created by Kaan Baris Bayrak on 21/10/2020.
//

enum class HopperError {
    MISSING_URL,
    MISSING_ACCESS_TOKEN,
    MISSING_CREDENTIALS,
    MISSING_REFRESH_TOKEN,
    ACCESS_TOKEN_EXPIRED,
    INVALID_ACCESS_TOKEN,
    INVALID_SESSION,
    BAD_REQUEST,
    UNAUTHORIZED,
    ENDPOINT_FORBIDDEN,
    ENDPOINT_NOT_FOUND,
    ENDPOINT_NOT_ALLOWED,
    API_LIMIT_EXCEED,
    SERVER_ERROR,
    SERVICE_UNAVAILABLE,
    UNKOWN_ERROR
}

